### ISSUE TITLE
为什么VirtualCore.startup放置Application类的attachBaseContext里？

### ISSUE THREAD

**Issue by prife** [prife/VirtualAppDoc#1]
为什么VirtualCore.startup放置Application类的attachBaseContext里，放onCreate里行不行？放activity的onCreate行不行？

**Comment by Howie-hxu** [comment]
首先，application的初始化是从：ActivityThread::handleBindApplication开始的。  
在这个函数中，简单来说初始化的顺序为  
1. call LoadedApk::makeApplication  
   
   > 这里最后会call到Application的attachBaseContext  
2. 之后会call ActivityThread::installContentProviders   
   
   > 这个函数会做content provider的初始化，会call到content provider的onCreate
3. 才会去call Instrumentation::callApplicationOnCreate   
   
   > 这里最后会call到Application的onCreate  

---

通过代码，我们发现在call完VirtualCore.startup以后，会把isStartUp的变量置为true  
而在BinderProvder（content provider对象，:x process），onCreate函数中会去查看这个变量，再往后做一些service的初始化。  

所以根据目前的代码flow，VirtualCore的startup必须要在content provider（BinderProvider）的onCreate之前做完，这样我们跑在process :x中的那些service（VXXXXService）才会被add到ServiceFetcher中，后面整个flow才可以跑通。  

---

回到问题，就目前的代码，在不改BinderProvider代码的情况下：
1. 为什么VirtualCore.startup放置Application类的attachBaseContext里  
   
   > 因为Application::attachBaseContext会在BinderProvider::onCreate之前触发  
2. 放onCreate里行不行？  
   
   > 不行，Application的onCreate晚于Content Provider的onCreate，remote service会得不到初始化
3. 放activity的onCreate行不行？   
   
   > 不行，Activity的onCreate比Application更晚，更加不行

**Comment by Howie-hxu** [comment]
这一块对于Process start的flow，可以参考：
[Begin Of Process：](https://github.com/prife/VirtualAppDoc/blob/master/docs/basic_knowledge/Begin_of_Process.md)
https://github.com/prife/VirtualAppDoc/blob/master/docs/basic_knowledge/Begin_of_Process.md
